export MINER_HOTKEY=""
export AWS_MINER_INSTANCE_ID=""
export MINER_INSTANCE_PORT=""
export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_REGION_NAME=""
export AWS_S3_BUCKET_NAME=""
export AWS_ROUTE53_HOSTED_ZONE_ID=""
export SQL_ALCHEMY_DB_URL=""
#export AUTO_HIDE_ORIGINAL_SERVER=""
#export AUTO_HIDE_DELAY_SEC="1200"

python bt_ddos_shield/miner_shield.py "$@"
